<?php

namespace DeviseBundle\Repository;

/**
 * SuiviDeviseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviDeviseRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *Renvoie les suivi à relancer
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findSuiviARelancer()
    {
        $dateMin = new \DateTime();
        $dateMin->sub(new \DateInterval('P1D'));
        return $this->createQueryBuilder('sd')
            ->join('sd.user', 'user')
            ->join('sd.devise', 'devise')
            ->select('sd, user, devise')
            ->where('(sd.dateAlerte is NULL or sd.dateAlerte < :date) AND (user.jourProchaineAlerte is NULL or user.jourProchaineAlerte  <:date) ')
            ->setParameter('date', $dateMin)
            ->andWhere('user.sendMailForAlert = :alerte_mail')
            ->setParameter('alerte_mail', true)
            ->getQuery()
            ->getResult();

    }
}
