<?php

namespace BookBundle\Repository;

/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteurRepository extends \Doctrine\ORM\EntityRepository
{
}
