<?php

namespace BookBundle\Repository;

/**
 * BaseLivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseLivreRepository extends \Doctrine\ORM\EntityRepository
{
}
