<?php

namespace BookBundle\Repository;

/**
 * EditeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditeurRepository extends \Doctrine\ORM\EntityRepository
{
}
