<?php

namespace CommunBundle\Repository;

/**
 * BatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatchRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Récupère la liste de tous les batchs
     * @return \Doctrine\ORM\Query
     */
    public function getQueryListBatch()
    {
        return $this->createQueryBuilder('b')
            ->getQuery();
    }
}
