<?php

namespace CommunBundle\Repository;

/**
 * BatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatchRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Récupère la liste de tous les batchs
     * @return \Doctrine\ORM\Query
     */
    public function getQueryListBatch()
    {
        return $this->createQueryBuilder('b')
            ->addOrderBy('dateDebut', 'DESC')
            ->getQuery();
    }

    /**
     * Retourne tous les batchs en cours
     * @return array
     */
    public function getBatchEnCours()
    {
        return $this->createQueryBuilder('b')
            ->select('b')
            ->where('b.dateFin is null')
            ->addOrderBy('b.dateDebut', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Retourne le dernier batch exécuté
     * @param $batchType
     * @return mixed
     */
    public function getDernierBatch($batchType)
    {
        return $this->createQueryBuilder('b')
            ->select('b')
            ->where('b.type=:type ')
            ->setParameter('type', $batchType)
            ->setMaxResults(1)
            ->addOrderBy('b.dateDebut', 'DESC')
            ->getQuery()
            ->getOneOrNullResult();
    }
}
