<?php

namespace CommunBundle\Repository;
use CommunBundle\Entity\Devise;

/**
 * CoursJourneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursJourneeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Calcule la moyenne d'un cours entre une date (max) et le nombre de jours d'avant pour une devise donnée
     * @param \DateTime $date
     * @param $nbDays
     * @param Devise $devise
     * @return int|mixed
     */
    public function getMoyenneCours(\DateTime $date, $nbDays, Devise $devise)
    {
        // From
        $from = clone($date);
        $from = $from->sub(new \DateInterval("P" . $nbDays . "D"));
        $out  = $this->createQueryBuilder('cj')
            ->select("avg(cj.cours) as cours")
            ->where('cj.date >= :from AND cj.date <= :to and cj.devise=:devise')
            ->setParameter('from', $from)
            ->setParameter('to', $date)
            ->setParameter('devise', $devise)
            ->getQuery()
            ->getOneOrNullResult();
        if (is_null($out) || is_null($out['cours'])) {
            $out["cours"] = 0;
        }
        return $out["cours"];


    }
}
