<?php

namespace CommunBundle\Repository;

/**
 * DeviseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviseRepository extends \Doctrine\ORM\EntityRepository
{
}
