<?php

namespace CommunBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Récupère une liste de news triée par date de mise en ligne
     * @param $maxNews
     * @return array
     */
    public function getListe($maxNews){
        return $this->createQueryBuilder('n')
            ->select('n')
            ->where('n.dateMiseEnLigne<:date')
            ->setParameter('date', new \DateTime())
            ->addOrderBy('n.dateMiseEnLigne', 'DESC')
            ->setMaxResults($maxNews)
            ->getQuery()
            ->getResult();
    }
}
