<?php

namespace CommunBundle\Repository;

/**
 * SuiviDeviseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviDeviseRepository extends \Doctrine\ORM\EntityRepository
{
}
