<?php

namespace LivreBundle\Repository;

/**
 * BaseLivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseLivreRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourne une query renvoyant des livres
     * @return \Doctrine\ORM\Query
     */
    public function getQueryListeLivre()
    {
        return $this->createQueryBuilder('l')
            ->addOrderBy('l.dateCreation', 'DESC')
            ->getQuery();
    }
}
