<?php

namespace LivreBundle\Repository;

/**
 * EtagereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtagereRepository extends \Doctrine\ORM\EntityRepository
{
}
