<?php

namespace LivreBundle\Repository;

/**
 * LivreLogWerserviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreLogWerserviceRepository extends \Doctrine\ORM\EntityRepository
{
}
