<?php

namespace LivreBundle\Repository;
use LivreBundle\Entity\BaseLivre;
use LivreBundle\Entity\Livre;
use UserBundle\Entity\User;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Vérifie si l'utilisateur possède le livre
     * @param BaseLivre $baseLivre
     * @param User $user
     * @return bool
     */
    public function utilisateurPossedeLivre(BaseLivre $baseLivre, User $user){
        return $this->createQueryBuilder('l')
            ->select('count(l)')
            ->where('l.baseLivre = :baseLivre AND l.proprietaire = :user')
            ->setParameter('baseLivre', $baseLivre)
            ->setParameter('user', $user)
            ->getQuery()
            ->getSingleScalarResult() >0;
    }
}
