<?php

namespace LivreBundle\Repository;

/**
 * MaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaisonRepository extends \Doctrine\ORM\EntityRepository
{
}
