<?php

namespace LivreBundle\Repository;

/**
 * MeubleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeubleRepository extends \Doctrine\ORM\EntityRepository
{
}
